language: java
jdk:
  - openjdk8

sudo: false



#travis running on ubuntu 14.04

before_install: 
#  - openssl aes-256-cbc -K $encrypted_5fef4fa28306_key -iv $encrypted_5fef4fa28306_iv -in codesigning.asc.enc -out codesigning.asc -d
#  - gpg --fast-import codesigning.asc


install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V --quiet 

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V --quiet

cache:
  directories:
    - '$HOME/.m2/repository'

deploy:
  - provider: script
    script: "mvn deploy -P assemble -DskipTests --quiet --settings mvn-settings.xml"
    skip_cleanup: true
    on:
      tags: false
      all_branches: true
      #deploy all branches to mvn if it is a snapshot version
      condition:  $(mvn -o -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)  = *"SNAPSHOT"* 
  
  - provider: script
    script: "mvn deploy -P assemble -DskipTests --quiet --settings mvn-settings.xml"
    skip_cleanup: true
    on:
      #deploy to maven if it is master branch and tagged
      tags: true
      branch: master
      
#above configuration prevents deploying a new release(not snapshot) if it is not tagged       
